CREATE TABLE "generationHistory" (
  "generationID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documentID" int,
  "generatedTimeStamp" timestamp,
  "documentVersion" int
);

CREATE TABLE "documents" (
  "documentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "styleID" int,
  "documentName" varchar(255),
  "documentContent" varchar(MAX)
);

CREATE TABLE "styles" (
  "styleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "styleName" varchar(20),
  "styleContent" varchar(MAX)
);

ALTER TABLE "documents" ADD FOREIGN KEY ("documentID") REFERENCES "generationHistory" ("documentID");

ALTER TABLE "styles" ADD FOREIGN KEY ("styleID") REFERENCES "documents" ("styleID");
