name: Deploy to Elastic Beanstalk

on:
  push:
    paths:
      - '.github/workflows/APIDeployment.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build API
      env:
        Database:ConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
      run: |
        cd Api
        dotnet restore Api.sln
        sudo dotnet build -c Release Api.sln

    - name: Publish API
      run: |
        cd Api
        sudo dotnet publish --self-contained -c Release -r linux-x64 --output ./publish Api.sln
        
    - name: Zip Published Files
      run: |
        cd Api/publish
        sudo zip -r ../publish.zip .
        ls -l ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-1'

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v15
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: 'eu-west-1'
        application_name: spectacular-generator-DotNetCSharpApplication-PBYS6X9YJ7MR
        environment_name: spectacular-generator
        version_label: v8
        deployment_package: Api/publish.zip
