name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build API
      run: |
        cd Api
        sudo dotnet build --self-contained -c Release -r linux-x64 Api.sln

    - name: Publish API
      run: |
        cd Api
        sudo dotnet publish --self-contained -c Release -r linux-x64 --output ./publish Api.sln


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-1'

    - name: Deploy to Elastic Beanstalk
      run: |
        cd Api
        cd publish 
        zip -r ../publish.zip .
        aws elasticbeanstalk create-application-version \
          --application-name "DotNetCSharpApplication" \
          --version-label "${GITHUB_SHA::7}" \
          --source-bundle "../publish.zip"
        aws elasticbeanstalk update-environment \
          --application-name "DotNetCSharpApplication" \
          --environment-name "spectacular-generator" \
          --version-label "${GITHUB_SHA::7}"


